// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACWfjP5I-wzsA380IAaFL2UdFjcWWFPMM',
    appId: '1:639435995014:web:b650197a9d709fe6dbde07',
    messagingSenderId: '639435995014',
    projectId: 'apora-364a2',
    authDomain: 'apora-364a2.firebaseapp.com',
    storageBucket: 'apora-364a2.firebasestorage.app',
    measurementId: 'G-2MWSXSBBQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZn399rAXQrxPTFEMO6yEbcXHpki3EYQ',
    appId: '1:639435995014:android:2f111edb8a8b4152dbde07',
    messagingSenderId: '639435995014',
    projectId: 'apora-364a2',
    storageBucket: 'apora-364a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9MVoSD2fPm6MwfmTBLXp1W8mqvHmOjhk',
    appId: '1:639435995014:ios:efec2480c863c0ccdbde07',
    messagingSenderId: '639435995014',
    projectId: 'apora-364a2',
    storageBucket: 'apora-364a2.firebasestorage.app',
    iosClientId: '639435995014-g20sik79brevecdn4f6kqs0vvlls50mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.apartmentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9MVoSD2fPm6MwfmTBLXp1W8mqvHmOjhk',
    appId: '1:639435995014:ios:efec2480c863c0ccdbde07',
    messagingSenderId: '639435995014',
    projectId: 'apora-364a2',
    storageBucket: 'apora-364a2.firebasestorage.app',
    iosClientId: '639435995014-g20sik79brevecdn4f6kqs0vvlls50mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.apartmentManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACWfjP5I-wzsA380IAaFL2UdFjcWWFPMM',
    appId: '1:639435995014:web:0bbbe28698108ebadbde07',
    messagingSenderId: '639435995014',
    projectId: 'apora-364a2',
    authDomain: 'apora-364a2.firebaseapp.com',
    storageBucket: 'apora-364a2.firebasestorage.app',
    measurementId: 'G-K3DC6KVLLV',
  );
}
